name: widget_recorder
description: Take images from any rendered `Widget` in the tree. Choose how to take the pictures using various controllers.
version: 0.3.0
homepage: https://github.com/RanfiCD/widget_recorder

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true